check-updates: true
debug-output: true
messages:
  no-permission: '&3You are not allowed to craft this item!'
  not-enough-xp: '&3You do not have enough XP to craft this item! Needed: %0XP - You have: %1XP'
  not-enough-lvl: '&3You do not have enough LVLs to craft this item! Needed LVL: %0'